/**
 * V2 seed data — Section → Topic only (no subtopics).
 * MERN: 37 core sections + an "Advanced / Optional" section that does NOT
 * count toward progress. DSA: 17 sections.
 */

const sec = (title, topics, { description = '', optional = false } = {}) => ({ title, description, optional, topics });

const t = (title, description = '') => ({ title, description });

export const mernSections = [
  sec('Web & Internet Fundamentals', [
    t('How the Web Works'),
    t('HTTP & HTTPS'),
    t('DNS Explained'),
    t('Browsers & How Pages Render'),
    t('Client–Server Architecture'),
    t('URLs, Ports & REST Basics'),
  ], { description: 'The foundations of how the internet, browsers and APIs fit together.' }),
  sec('HTML', [
    t('HTML Basics & Document Structure'),
    t('Text, Links & Images'),
    t('Lists & Tables'),
    t('Forms & Inputs'),
    t('Semantic HTML'),
    t('HTML5 Media & Canvas'),
    t('Accessibility Basics (a11y)'),
  ], { description: 'Markup fundamentals — structure, semantics and accessible pages.' }),
  sec('CSS', [
    t('CSS Basics & Connecting Stylesheets'),
    t('Selectors, Specificity & Cascade'),
    t('The Box Model'),
    t('Typography & Units'),
    t('Colors & Backgrounds'),
    t('Flexbox'),
    t('CSS Grid'),
    t('Positioning & Z-index'),
    t('Transitions & Animations'),
    t('CSS Custom Properties'),
  ], { description: 'Styling the web — layout, design and modern CSS features.' }),
  sec('Responsive Web Design', [
    t('Media Queries & Breakpoints'),
    t('Mobile-First Design'),
    t('Fluid Layouts & Clamp'),
    t('Responsive Units (vh, vw, %)'),
    t('Responsive Images'),
    t('Responsive Navbar & Cards'),
    t('Container Queries'),
    t('Testing & DevTools Responsive Mode'),
  ], { description: 'Layouts that adapt to every screen size.' }),
  sec('SCSS / SASS', [
    t('SASS Setup & Compilation'),
    t('Variables & Nesting'),
    t('Mixins & Functions'),
    t('Partials & @use/@import'),
    t('Extends & Placeholders'),
    t('Using SCSS with Vite'),
  ], { description: 'Write cleaner, reusable CSS with a preprocessor.' }),
  sec('JavaScript Fundamentals', [
    t('Variables: var, let & const'),
    t('Data Types & typeof'),
    t('Operators & Precedence'),
    t('Type Coercion & == vs ==='),
    t('Template Literals'),
  ], { description: 'The building blocks of the language.' }),
  sec('JavaScript Control Flow', [
    t('Conditional Statements (if/else)'),
    t('Switch Statements'),
    t('Loops: for, while & do-while'),
    t('Loop Control: break & continue'),
    t('for...of & Iterables'),
  ], { description: 'Decision making and repetition.' }),
  sec('JavaScript Functions', [
    t('Function Basics & Parameters'),
    t('Arrow Functions'),
    t('Rest, Spread & Defaults'),
    t('Scope & Closures'),
    t('Higher-Order Functions'),
    t('IIFE & Call Patterns'),
  ], { description: 'Reusable logic and functional patterns.' }),
  sec('Arrays & Objects', [
    t('Array Basics & Methods'),
    t('map, filter & reduce'),
    t('Array Iteration Idioms'),
    t('Objects & Property Access'),
    t('Object Spread & Destructuring'),
    t('Nested Data & Deep Access'),
  ], { description: 'Working with the most common data structures in JS.' }),
  sec('DOM Manipulation', [
    t('What is the DOM?'),
    t('Selecting Elements'),
    t('Traversing the DOM'),
    t('Creating & Removing Elements'),
    t('innerHTML vs textContent'),
    t('Styles & Classes'),
  ], { description: 'Interacting with the page documents.' }),
  sec('Events & Browser APIs', [
    t('Event Listeners'),
    t('The Event Object'),
    t('Event Bubbling & Delegation'),
    t('Keyboard & Mouse Events'),
    t('Web Storage (localStorage/sessionStorage)'),
    t('Timers: setTimeout & setInterval'),
    t('Geolocation & Other Browser APIs'),
  ], { description: 'Responding to users and using built-in browser services.' }),
  sec('Advanced JavaScript', [
    t('Scope, Hoisting & Execution Context'),
    t('Closures in Depth'),
    t('this & Explicit Binding'),
    t('Prototypes & Classes'),
    t('ES Modules (import/export)'),
    t('Callbacks & Callback Hell'),
    t('Promises & Chaining'),
    t('async / await'),
    t('The Fetch API'),
    t('The Event Loop & Microtasks'),
    t('Error Handling: try/catch & throw'),
    t('Optional Chaining & Nullish Coalescing'),
  ], { description: 'Async programming and the deeper mechanics of the language.' }),
  sec('Git & GitHub', [
    t('Git Basics & Initialization'),
    t('Commits & History'),
    t('Branching & Merging'),
    t('Working with Remote Repos'),
    t('Pull Requests'),
    t('.gitignore & Best Practices'),
    t('Resolving Conflicts'),
    t('Git Workflows (feature-branch flow)'),
  ], { description: 'Version control essentials for every project.' }),
  sec('React', [
    t('What is React & JSX'),
    t('Components & Props'),
    t('Conditional Rendering'),
    t('Lists & Keys'),
    t('useState & Events'),
    t('Lifting State Up'),
    t('React DevTools'),
    t('Thinking in Components'),
  ], { description: 'Building UIs from components with React.' }),
  sec('React Hooks', [
    t('useState in Depth'),
    t('useEffect & Lifecycle'),
    t('Rules of Hooks'),
    t('useContext'),
    t('useReducer'),
    t('useRef'),
    t('useMemo & useCallback'),
    t('Custom Hooks'),
    t('useLayoutEffect'),
  ], { description: 'State and side effects in function components.' }),
  sec('React Router', [
    t('Setup, Routes & BrowserRouter'),
    t('Link, NavLink & Nested Routes'),
    t('Route Parameters'),
    t('Query Strings & Search Params'),
    t('useNavigate & Redirects'),
    t('Layout & Outlet Routes'),
    t('Protected Routes'),
  ], { description: 'Client-side navigation for SPAs.' }),
  sec('State Management / Redux', [
    t('When to Use Global State'),
    t('Context + useReducer'),
    t('Redux Toolkit Setup'),
    t('Slices, Actions & Reducers'),
    t('useSelector & useDispatch'),
    t('Async Thunks (createAsyncThunk)'),
    t('RTK Query vs Thunks'),
    t('Zustand (lighter alternative)'),
  ], { description: 'Managing shared application state predictably.' }),
  sec('React Forms & API Integration', [
    t('Controlled Components'),
    t('Form Validation'),
    t('Data Fetching with fetch/axios'),
    t('Loading & Error States'),
    t('Axios Interceptors'),
    t('Uploading Files from React'),
    t('Data-Fetching Custom Hooks'),
  ], { description: 'Forms and talking to your backend from React.' }),
  sec('React Performance', [
    t('React.memo & Pure Components'),
    t('useCallback / useMemo Strategies'),
    t('Code Splitting & React.lazy'),
    t('Virtualized Lists'),
    t('Avoiding Unnecessary Re-renders'),
    t('React Profiler'),
  ], { description: 'Keeping React apps fast at scale.' }),
  sec('React Deployment', [
    t('Creating a Production Build'),
    t('Environment Variables in Vite'),
    t('Deploying to Vercel/Netlify'),
    t('Handling Static Assets'),
    t('Preview vs Production Builds'),
  ], { description: 'Shipping the frontend to production.' }),
  sec('Node.js', [
    t('What is Node.js'),
    t('Module System: CommonJS & ESM'),
    t('npm & package.json'),
    t('The Event Loop'),
    t('fs, path & the os Module'),
    t('Streams & Buffers'),
    t('Building a CLI / Server with Node'),
  ], { description: 'JavaScript on the server.' }),
  sec('Backend Architecture / MVC', [
    t('The MVC Pattern'),
    t('Project Structure & Separation of Concerns'),
    t('Config & Environment Files'),
    t('Designing Routes & Controllers'),
    t('REST-style Resource Design'),
  ], { description: 'Organizing backend code so it scales cleanly.' }),
  sec('Express.js', [
    t('Getting Started with Express'),
    t('Routing Basics'),
    t('Route Params & Query Strings'),
    t('Express Middleware'),
    t('Parsing JSON & CORS'),
    t('Serving Static Files'),
    t('Express Routers & Modularity'),
    t('Central Error Handling'),
  ], { description: 'The standard Node.js web framework.' }),
  sec('EJS', [
    t('EJS Setup & Rendering'),
    t('Templates, Layouts & Partials'),
    t('Passing Data to Views'),
    t('Conditionals & Loops in EJS'),
    t('Linking Static Assets'),
  ], { description: 'Server-side templating with JavaScript.' }),
  sec('File Uploads', [
    t('Multer Setup & Storage'),
    t('Single vs Multiple Uploads'),
    t('Validating Size & File Type'),
    t('Serving Uploaded Files'),
    t('Cloud Storage (Cloudinary)'),
  ], { description: 'Accepting and handling user uploads securely.' }),
  sec('MongoDB & Mongoose', [
    t('MongoDB Concepts & Atlas'),
    t('Mongoose Setup & Connection'),
    t('Schemas & Models'),
    t('CRUD Operations'),
    t('Schema Validation & Defaults'),
    t('References & Populate'),
    t('Aggregation Framework'),
    t('Indexes'),
  ], { description: 'Data persistence with a document database.' }),
  sec('REST APIs', [
    t('REST Principles & Resources'),
    t('Designing CRUD Endpoints'),
    t('HTTP Status Codes'),
    t('Request & Response Formats'),
    t('API Versioning'),
    t('Documenting APIs'),
  ], { description: 'Building clean, predictable HTTP APIs.' }),
  sec('API Security', [
    t('Authentication vs Authorization'),
    t('Rate Limiting'),
    t('Security Headers (Helmet)'),
    t('CORS Policies'),
    t('Input Sanitization'),
    t('JWT Security Best Practices'),
    t('Secure Cookies & HTTPS'),
  ], { description: 'Protecting your backend from common attacks.' }),
  sec('MongoDB Optimization', [
    t('Indexing Strategies'),
    t('Optimizing Aggregations'),
    t('Data Modeling for Performance'),
    t('Query Optimization & explain()'),
    t('Lean Queries with Mongoose'),
  ], { description: 'Making database operations fast and efficient.' }),
  sec('Backend Logging', [
    t('Why Logging Matters'),
    t('winston & morgan'),
    t('Log Levels & Formatting'),
    t('Request & Error Logging'),
    t('Storing Logs'),
  ], { description: 'Observability for your backend.' }),
  sec('Production Backend', [
    t('Process Managers (PM2)'),
    t('Environment Config in Production'),
    t('Compression & Caching Headers'),
    t('Health Checks & Monitoring'),
    t('Graceful Shutdown'),
  ], { description: 'Hardening and operating the server in production.' }),
  sec('Authentication & Authorization', [
    t('Hashing Passwords with bcrypt'),
    t('JWT Fundamentals'),
    t('httpOnly Cookies & Sessions'),
    t('Auth Middleware (protect)'),
    t('Roles & Permissions'),
    t('Refresh Tokens'),
    t('OAuth / Third-party Login Basics'),
  ], { description: 'Secure identity and access control.' }),
  sec('WebSockets / Socket.IO', [
    t('The WebSocket Protocol'),
    t('Socket.IO Setup & Events'),
    t('Rooms & Namespaces'),
    t('Emitting & Broadcasting'),
    t('Real-time Chat Example'),
    t('Online Presence & Typing Indicators'),
  ], { description: 'Real-time, bidirectional communication.' }),
  sec('Redis & Caching', [
    t('What is Redis'),
    t('Caching API Responses'),
    t('Sessions in Redis'),
    t('Pub/Sub'),
    t('Job Queues (Bull)'),
    t('Rate Limiting with Redis'),
  ], { description: 'In-memory data store for speed and background work.' }),
  sec('Error Handling', [
    t('try/catch & Async Wrappers'),
    t('Express Global Error Middleware'),
    t('Handling Validation Errors'),
    t('404s & Not Found'),
    t('Unhandled Rejections'),
    t('Client-side Error States'),
  ], { description: 'Fail gracefully at every layer.' }),
  sec('Testing', [
    t('Unit Testing with Jest'),
    t('React Testing Library'),
    t('API Testing with Supertest'),
    t('Mocking & Fixtures'),
    t('Integration Tests'),
    t('E2E with Playwright'),
  ], { description: 'Confidence through automated tests.' }),
  sec('Deployment', [
    t('Vercel for the Frontend'),
    t('Render/Railway/Heroku for the Backend'),
    t('MongoDB Atlas in Production'),
    t('Env Vars & Secrets Management'),
    t('HTTPS & Domain Setup'),
    t('Full-Stack Deployment Checklist'),
  ], { description: 'Getting the whole stack live on the internet.' }),
];

export const mernOptionalSections = [
  sec('Advanced / Optional', [
    t('Three.js / React Three Fiber'),
    t('Microservices'),
    t('Next.js'),
    t('Web3'),
    t('Docker'),
    t('Kubernetes'),
  ], { description: 'Extra topics kept separate — these do not count toward core MERN progress.', optional: true }),
];

export const dsaSections = [
  sec('Conditional Statements', [
    t('if / else Statements'),
    t('else if & Nested Conditions'),
    t('Switch Statements'),
    t('Ternary & Logical Operators'),
    t('Truthy & Falsy Values'),
  ], { description: 'Making decisions in code.' }),
  sec('Loops & Pattern Programming', [
    t('for Loops'),
    t('while & do-while Loops'),
    t('Nested Loops'),
    t('Loop Control: break & continue'),
    t('Basic Pattern Printing'),
    t('Star & Triangle Patterns'),
    t('Number Patterns'),
    t('Character Patterns'),
  ], { description: 'Repetition and pattern-based problem solving.' }),
  sec('Arrays', [
    t('Array Basics (Declaration & Access)'),
    t('Reading & Writing Arrays'),
    t('Common Array Methods'),
    t('Array Traversal'),
    t('Reversing an Array'),
    t('Intro to 2D Arrays'),
  ], { description: 'The most important linear data structure.' }),
  sec('OOP in JavaScript', [
    t('Classes & Objects'),
    t('Constructors & the new Keyword'),
    t('Properties & Methods'),
    t('Inheritance & super'),
    t('Encapsulation & Getters/Setters'),
    t('Static Methods'),
    t('The this Keyword (Advanced)'),
  ], { description: 'Object-oriented programming in JavaScript.' }),
  sec('Strings', [
    t('String Basics & Literals'),
    t('Common String Methods'),
    t('String Comparison & Immutability'),
    t('String Traversal'),
    t('Template Strings & Interpolation'),
  ], { description: 'Manipulating text efficiently.' }),
  sec('Time & Space Complexity', [
    t('Big O Notation'),
    t('Common Complexities (O(1), O(n), O(n²), O(log n))'),
    t('Analyzing Nested Loops'),
    t('Space Complexity & Auxiliary Space'),
    t('Best, Worst & Average Case'),
  ], { description: 'Measuring and optimizing algorithm efficiency.' }),
  sec('Mathematics & Algorithms', [
    t('Counting Digits'),
    t('LCM & GCD'),
    t('Prime Numbers & Sieve'),
    t('Factorials'),
    t('Palindrome & Armstrong Numbers'),
    t('Fibonacci Series'),
    t('Modular Arithmetic'),
  ], { description: 'Classic number-based algorithms.' }),
  sec('Advanced Arrays', [
    t('Two Pointers'),
    t('Prefix Sum'),
    t('Sliding Window'),
    t("Kadane's Algorithm"),
    t('Stock Buy & Sell'),
    t('Rotate Array'),
    t('Intro to Merge Intervals'),
  ], { description: 'Patterns for harder array problems.' }),
  sec('Sorting', [
    t('Bubble Sort'),
    t('Selection Sort'),
    t('Insertion Sort'),
    t('Merge Sort'),
    t('Quick Sort'),
    t('Counting & Radix Sort (Intro)'),
    t('Stable vs Unstable Sorts'),
  ], { description: 'Ordering data with different algorithms.' }),
  sec('Binary Search', [
    t('Binary Search Basics'),
    t('Lower & Upper Bound'),
    t('First & Last Occurrence'),
    t('Search in a Rotated Sorted Array'),
    t('Binary Search on Answer'),
    t('Search in a 2D Matrix'),
  ], { description: 'Searching efficiently in sorted data.' }),
  sec('Hashing', [
    t('HashMap & HashSet Basics'),
    t('Frequency Counting'),
    t('Two Sum & Pair Problems'),
    t('Longest Consecutive Sequence'),
    t('Subarray Sum Equals K'),
    t('Collision Handling'),
  ], { description: 'O(1) lookups with hash-based structures.' }),
  sec('Linked List', [
    t('Singly Linked List Basics'),
    t('Insertion & Deletion'),
    t('Traversal & Middle Node'),
    t('Reversing a Linked List'),
    t('Cycle Detection (Floyd)'),
    t('Merging Two Sorted Lists'),
    t('Removing Duplicates & Union'),
  ], { description: 'Linear structures with pointers.' }),
  sec('Queue', [
    t('Queue Basics (FIFO)'),
    t('Array & Linked-List Queues'),
    t('Circular Queue'),
    t('Queue Using Stacks'),
    t('Deque & Sliding Window Maximum'),
  ], { description: 'First-in, first-out data handling.' }),
  sec('Stack', [
    t('Stack Basics (LIFO)'),
    t('Array & Linked-List Stacks'),
    t('Balanced Parentheses'),
    t('Next Greater Element'),
    t('Monotonic Stack'),
    t('Evaluate Postfix / Prefix'),
    t('Min Stack'),
  ], { description: 'Last-in, first-out data handling.' }),
  sec('Recursion & Backtracking', [
    t('Recursion Basics & Base Cases'),
    t('Recursion with Arrays & Strings'),
    t('Subsets & Permutations'),
    t('The N-Queens Problem'),
    t('Rat in a Maze'),
    t('Backtracking: Sudoku Solver'),
  ], { description: 'Solving problems by solving smaller versions of themselves.' }),
  sec('Binary Trees', [
    t('Tree Basics & Structure'),
    t('Inorder, Preorder & Postorder'),
    t('Level Order Traversal'),
    t('Height & Depth of a Tree'),
    t('Diameter & Lowest Common Ancestor'),
    t('Left, Right, Top & Bottom Views'),
    t('Symmetric Tree & Path Sum'),
  ], { description: 'Hierarchical data and tree algorithms.' }),
  sec('Binary Search Tree', [
    t('BST Basics & Properties'),
    t('Searching in a BST'),
    t('Insertion & Deletion'),
    t('Floor & Ceil in a BST'),
    t('Validate a BST'),
    t('Kth Smallest/Largest Element'),
    t('Sorted Array to Balanced BST'),
  ], { description: 'Ordered binary trees for fast search and insert.' }),
];

export const pcmSections = [
  sec('Physics', [
    t('Units & Measurements'),
    t('Kinematics'),
    t('Laws of Motion'),
    t('Work, Energy & Power'),
    t('System of Particles & Rotational Motion'),
    t('Gravitation'),
    t('Properties of Matter'),
    t('Thermodynamics'),
    t('Kinetic Theory'),
    t('Oscillations'),
    t('Waves'),
    t('Electrostatics'),
    t('Current Electricity'),
    t('Moving Charges & Magnetism'),
    t('Magnetism & Matter'),
    t('Electromagnetic Induction'),
    t('Alternating Current'),
    t('Electromagnetic Waves'),
    t('Ray Optics'),
    t('Wave Optics'),
    t('Dual Nature of Matter & Radiation'),
    t('Atoms'),
    t('Nuclei'),
    t('Semiconductor Electronics'),
  ], { description: 'Mechanics, electromagnetism, optics and modern physics.' }),
  sec('Chemistry', [
    t('Some Basic Concepts of Chemistry'),
    t('Structure of Atom'),
    t('Classification of Elements & Periodicity'),
    t('Chemical Bonding'),
    t('Thermodynamics'),
    t('Equilibrium'),
    t('Redox Reactions'),
    t('Organic Chemistry Basics'),
    t('Hydrocarbons'),
    t('Solutions'),
    t('Electrochemistry'),
    t('Chemical Kinetics'),
    t('Surface Chemistry'),
    t('Coordination Compounds'),
    t('d- and f-Block Elements'),
    t('Haloalkanes & Haloarenes'),
    t('Alcohols, Phenols & Ethers'),
    t('Aldehydes, Ketones & Carboxylic Acids'),
    t('Amines'),
    t('Biomolecules'),
    t('Polymers'),
    t('Chemistry in Everyday Life'),
  ], { description: 'Physical, organic and inorganic chemistry.' }),
  sec('Mathematics', [
    t('Sets & Relations'),
    t('Functions'),
    t('Trigonometry'),
    t('Complex Numbers'),
    t('Quadratic Equations'),
    t('Sequences & Series'),
    t('Permutations & Combinations'),
    t('Binomial Theorem'),
    t('Straight Lines'),
    t('Circles'),
    t('Conic Sections'),
    t('Limits & Continuity'),
    t('Differentiation'),
    t('Applications of Derivatives'),
    t('Integrals'),
    t('Applications of Integrals'),
    t('Differential Equations'),
    t('Matrices'),
    t('Determinants'),
    t('Vector Algebra'),
    t('Three-Dimensional Geometry'),
    t('Probability'),
    t('Statistics'),
  ], { description: 'Algebra, calculus, geometry, vectors and probability.' }),
];

export const buildMernTemplate = () => ({
  title: 'MERN Stack',
  icon: 'Code',
  subject: 'mern',
  description: 'The complete MERN curriculum — web fundamentals through React, Node.js, MongoDB and production deployment.',
  sections: [...mernSections, ...mernOptionalSections],
});

export const buildDsaTemplate = () => ({
  title: 'DSA with JavaScript',
  icon: 'Network',
  subject: 'dsa',
  description: 'Data Structures & Algorithms in JavaScript — from conditionals and patterns to strings, sorting, recursion and trees.',
  sections: [...dsaSections],
});

export const buildPcmTemplate = () => ({
  title: 'PCM',
  icon: 'Atom',
  subject: 'pcm',
  description: 'Physics • Chemistry • Mathematics — the complete Class 11–12 PCM syllabus for competitive preparation.',
  sections: [...pcmSections],
});