/**
 * MERN stack syllabus — master/default data used by the seed script.
 * Structure: modules > topics > subtopics.
 * Official content is marked as isCustom:false with createdBy:null by the seeder.
 */

export const syllabusData = [
  {
    title: 'HTML',
    description: 'The foundation of every web page — structure, semantics and accessible markup.',
    topics: [
      {
        title: 'HTML Basics',
        description: 'Getting started with markup.',
        subtopics: [
          {
            title: 'Introduction to HTML',
            description: 'What HTML is and how the browser renders it.',
            difficulty: 'easy',
            estimatedTime: '30 min',
            resources: [
              { title: 'MDN: HTML basics', url: 'https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics', type: 'documentation' },
            ],
          },
          {
            title: 'HTML Document Structure',
            description: 'Doctype, head, body and the skeleton of a page.',
            difficulty: 'easy',
            estimatedTime: '30 min',
            resources: [],
          },
          {
            title: 'Tags & Elements',
            description: 'Common tags, nesting and void elements.',
            difficulty: 'easy',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Attributes',
            description: 'Global attributes (id, class, data-*, alt, href).',
            difficulty: 'easy',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Comments & Formatting',
            description: 'Writing readable, well-formatted markup.',
            difficulty: 'easy',
            estimatedTime: '20 min',
            resources: [],
          },
        ],
      },
      {
        title: 'Text, Links & Images',
        description: 'The everyday content elements.',
        subtopics: [
          {
            title: 'Headings & Paragraphs',
            description: 'Semantic text hierarchy.',
            difficulty: 'easy',
            estimatedTime: '30 min',
            resources: [],
          },
          {
            title: 'Links & Anchors',
            description: 'Inline, external and fragment links.',
            difficulty: 'easy',
            estimatedTime: '40 min',
            resources: [],
          },
          {
            title: 'Images & Figure',
            description: 'img, alt text, figure and figcaption.',
            difficulty: 'easy',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Lists',
            description: 'Ordered, unordered and description lists.',
            difficulty: 'easy',
            estimatedTime: '30 min',
            resources: [],
          },
        ],
      },
      {
        title: 'Tables & Forms',
        description: 'Tabular data and user input.',
        subtopics: [
          {
            title: 'Tables',
            description: 'table, thead, tbody, colspan and rowspan.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Forms & Inputs',
            description: 'form, input types, labels and validation attributes.',
            difficulty: 'medium',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Select, Textarea & Buttons',
            description: 'Control elements for richer forms.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Semantic HTML',
            description: 'header, nav, main, section, article, footer.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
        ],
      },
    ],
  },
  {
    title: 'CSS Fundamentals',
    description: 'Styling the web — selectors, box model, layout and responsive design.',
    topics: [
      {
        title: 'CSS Basics',
        description: 'How CSS applies styles.',
        subtopics: [
          {
            title: 'Connecting CSS to HTML',
            description: 'Link, inline and embedded styling.',
            difficulty: 'easy',
            estimatedTime: '30 min',
            resources: [],
          },
          {
            title: 'Selectors',
            description: 'Element, class, id, attribute and combinator selectors.',
            difficulty: 'easy',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Specificity & Cascade',
            description: 'How conflicting rules resolve.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Box Model',
            description: 'Margin, border, padding and content.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Colors & Backgrounds',
            description: 'Named, hex, rgb, gradients and background images.',
            difficulty: 'easy',
            estimatedTime: '45 min',
            resources: [],
          },
        ],
      },
      {
        title: 'Typography',
        description: 'Text styling and web fonts.',
        subtopics: [
          {
            title: 'Fonts & Units',
            description: 'px, em, rem, % and vw/vh.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Text Properties',
            description: 'font-family, weight, letter-spacing, line-height.',
            difficulty: 'easy',
            estimatedTime: '40 min',
            resources: [],
          },
          {
            title: 'Web Fonts & Icons',
            description: 'Google Fonts, @font-face and icon fonts.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
        ],
      },
      {
        title: 'Flexbox',
        description: 'Modern one-dimensional layout.',
        subtopics: [
          {
            title: 'Flex Container & Items',
            description: 'display:flex and the flex model.',
            difficulty: 'easy',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Main Axis & Cross Axis',
            description: 'flex-direction and row/column flows.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Justify & Align',
            description: 'justify-content, align-items, align-self and gap.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Flex Grow, Shrink & Wrap',
            description: 'flex-basis, flex-grow, flex-shrink and flex-wrap.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
        ],
      },
      {
        title: 'Grid & Positioning',
        description: 'Two-dimensional layout and positioning contexts.',
        subtopics: [
          {
            title: 'CSS Grid Basics',
            description: 'grid-template-columns/rows and the grid model.',
            difficulty: 'medium',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Grid Areas & Placement',
            description: 'grid-area, grid-column and grid-row.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Positioning',
            description: 'static, relative, absolute, fixed and sticky.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Z-index & Stacking',
            description: 'Stacking context and layering elements.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
        ],
      },
      {
        title: 'Responsive Design',
        description: 'Layouts that adapt to any screen.',
        subtopics: [
          {
            title: 'Media Queries',
            description: 'Breakpoints and adaptive rules.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Mobile-First Approach',
            description: 'Build for small screens first, then enhance.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Fluid Layouts',
            description: 'Clamp, max-width and container queries.',
            difficulty: 'hard',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Responsive Navbar & Cards',
            description: 'Practical responsive components.',
            difficulty: 'medium',
            estimatedTime: '1.5 hours',
            resources: [],
          },
        ],
      },
    ],
  },
  {
    title: 'JavaScript Essentials',
    description: 'Core language — variables, operators, control flow and functions.',
    topics: [
      {
        title: 'Variables & Data Types',
        description: 'The building blocks of JS.',
        subtopics: [
          {
            title: 'var, let & const',
            description: 'Declaration, reassignment and best practices.',
            difficulty: 'easy',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Primitive & Reference Types',
            description: 'Number, string, boolean, null, undefined, object.',
            difficulty: 'easy',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Type Coercion & == vs ===',
            description: 'How JavaScript converts and compares values.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Scope & Closures',
            description: 'Global, function and block scope; closures.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
        ],
      },
      {
        title: 'Operators & Control Flow',
        description: 'Logic and decision making.',
        subtopics: [
          {
            title: 'Arithmetic & Comparison',
            description: 'Basic operators and comparisons.',
            difficulty: 'easy',
            estimatedTime: '30 min',
            resources: [],
          },
          {
            title: 'Logical Operators',
            description: '&&, || and short-circuit evaluation.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'if / else & switch',
            description: 'Conditional branching.',
            difficulty: 'easy',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Ternary & Optional Chaining',
            description: 'Concise conditionals and safe access.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
        ],
      },
      {
        title: 'Functions',
        description: 'Reusable blocks of logic.',
        subtopics: [
          {
            title: 'Function Basics',
            description: 'Declarations, expressions and parameters.',
            difficulty: 'easy',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Arrow Functions',
            description: 'Shorter syntax and lexical this.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Parameters & Defaults',
            description: 'Rest params, default values and arguments.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Higher-Order Functions',
            description: 'Functions returning/taking functions (callbacks).',
            difficulty: 'hard',
            estimatedTime: '1 hour',
            resources: [],
          },
        ],
      },
      {
        title: 'Arrays & Objects',
        description: 'Working with data structures.',
        subtopics: [
          {
            title: 'Array Methods',
            description: 'push, pop, slice, splice, includes, indexOf.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'map, filter & reduce',
            description: 'Core functional array transformations.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'forEach & for...of',
            description: 'Iteration idioms.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Object Manipulation',
            description: 'Dot vs bracket, spreading, destructuring.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
        ],
      },
      {
        title: 'ES6+ Features',
        description: 'Modern JavaScript syntax.',
        subtopics: [
          {
            title: 'Template Literals',
            description: 'String interpolation and multi-line strings.',
            difficulty: 'easy',
            estimatedTime: '30 min',
            resources: [],
          },
          {
            title: 'Destructuring',
            description: 'Objects and arrays destructuring patterns.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Spread & Rest Operators',
            description: 'Copying, merging and gathering values.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Modules (import/export)',
            description: 'Splitting code across files.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Classes & this',
            description: 'Syntactic sugar over prototypes, context binding.',
            difficulty: 'hard',
            estimatedTime: '1 hour',
            resources: [],
          },
        ],
      },
    ],
  },
  {
    title: 'DOM & Events',
    description: 'Interacting with the page.',
    topics: [
      {
        title: 'Document Object Model',
        subtopics: [
          {
            title: 'What is the DOM?',
            description: 'How the browser models the page.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Selecting Elements',
            description: 'getElementById, querySelector, querySelectorAll.',
            difficulty: 'easy',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Traversing the DOM',
            description: 'Parent, children and sibling navigation.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Creating & Removing Elements',
            description: 'createElement, append, remove and innerHTML.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
        ],
      },
      {
        title: 'Events',
        subtopics: [
          {
            title: 'Event Listeners',
            description: 'addEventListener and inline handlers.',
            difficulty: 'easy',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Event Object',
            description: 'target, currentTarget, preventDefault.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Event Bubbling & Delegation',
            description: 'Propagating events and handling them efficiently.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
        ],
      },
    ],
  },
  {
    title: 'Advanced JavaScript',
    description: 'Asynchronous programming, the event loop and deeper concepts.',
    topics: [
      {
        title: 'Asynchronous JavaScript',
        subtopics: [
          {
            title: 'Synchronous vs Asynchronous',
            description: 'Blocking, the call stack and the event loop.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Callbacks',
            description: 'Callback pattern and callback hell.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Promises',
            description: 'Promise states, then/catch and chaining.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'async / await',
            description: 'Synchronous-looking async code.',
            difficulty: 'hard',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Promise.all & race',
            description: 'Working with multiple promises.',
            difficulty: 'hard',
            estimatedTime: '1 hour',
            resources: [],
          },
        ],
      },
      {
        title: 'The Fetch API',
        subtopics: [
          {
            title: 'Making Requests',
            description: 'GET, POST and status handling with fetch.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Handling JSON',
            description: 'Parsing and transforming API responses.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Error Handling',
            description: 'try/catch, .catch and network failures.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
        ],
      },
    ],
  },
  {
    title: 'React.js',
    description: 'Component-based UI development with hooks and routing.',
    topics: [
      {
        title: 'React Fundamentals',
        subtopics: [
          {
            title: 'Component Thinking',
            description: 'What makes React special — virtual DOM, JSX.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'JSX',
            description: 'JavaScript in markup, expressions.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Components & Props',
            description: 'Composition, props and .map() rendering.',
            difficulty: 'medium',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Conditional Rendering',
            description: 'ternary, &&, switch toggling UI.',
            difficulty: 'easy',
            estimatedTime: '45 min',
            resources: [],
          },
        ],
      },
      {
        title: 'State & Lifecycle',
        subtopics: [
          {
            title: 'useState',
            description: 'Managing component state.',
            difficulty: 'medium',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Lifting State Up',
            description: 'Sharing state between components.',
            difficulty: 'medium',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'useEffect',
            description: 'Side effects, cleanups and dependencies.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Lists & Keys',
            description: 'Keys, map rendering and reconciliation.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Forms & Events',
            description: 'Controlled components and two-way binding.',
            difficulty: 'medium',
            estimatedTime: '1.5 hours',
            resources: [],
          },
        ],
      },
      {
        title: 'Advanced React',
        subtopics: [
          {
            title: 'React Router',
            description: 'Routing, navigation and nested routes.',
            difficulty: 'medium',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Context API',
            description: 'Prop drilling solved with provider/consumer.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Custom Hooks',
            description: 'Extracting reusable logic.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'useRef & useMemo',
            description: 'Referencing values and performance.',
            difficulty: 'hard',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Fetching Data in React',
            description: 'APIs, loading states and error states.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
        ],
      },
    ],
  },
  {
    title: 'Node.js & Express',
    description: 'Server-side JavaScript and REST APIs.',
    topics: [
      {
        title: 'Node.js Basics',
        subtopics: [
          {
            title: 'What is Node.js?',
            description: 'The runtime, modules and npm.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'JavaScript Modules',
            description: 'CommonJS, require and exports.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'npm & package.json',
            description: 'Installing deps, scripts, semantic versions.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'File System & fs',
            description: 'Reading and writing files.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
        ],
      },
      {
        title: 'Express Fundamentals',
        subtopics: [
          {
            title: 'Your First Server',
            description: 'express() app, listening to ports.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
          {
            title: 'Routing',
            description: 'GET/POST/PUT/DELETE and route params.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Middleware',
            description: 'Express middleware chain, custom middleware.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Parsing JSON & CORS',
            description: 'body-parser, requests from the browser.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
        ],
      },
      {
        title: 'REST API Design',
        subtopics: [
          {
            title: 'REST Principles',
            description: 'Resources, verbs and status codes.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'CRUD Endpoints',
            description: 'Building full CRUD for a resource.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Error Handling',
            description: 'Central error middleware and responses.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Environment Variables',
            description: 'dotenv, secrets and config.',
            difficulty: 'easy',
            estimatedTime: '30 min',
            resources: [],
          },
        ],
      },
    ],
  },
  {
    title: 'Authentication & MongoDB',
    description: 'Secure auth and data persistence.',
    topics: [
      {
        title: 'Authentication',
        subtopics: [
          {
            title: 'Hashing Passwords',
            description: 'bcrypt — hashing and comparing.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'JWT Fundamentals',
            description: 'Tokens, payloads, signing and verifying.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Auth Middleware',
            description: 'Protecting routes and user identity.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Authorization vs AuthN',
            description: 'Who you are vs what you can do.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
        ],
      },
      {
        title: 'MongoDB',
        subtopics: [
          {
            title: 'Introduction to MongoDB',
            description: 'Documents, collections and the Atlas cloud.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'CRUD Operations',
            description: 'Insert, find, update and delete documents.',
            difficulty: 'medium',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Mongoose Models',
            description: 'Schemas, models and validators.',
            difficulty: 'medium',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Relations & Populate',
            description: 'Referencing documents across collections.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Indexes & Aggregation',
            description: 'Speeding up queries and pipelines.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
        ],
      },
    ],
  },
  {
    title: 'Projects & Deployment',
    description: 'Building and shipping a full-stack app to production.',
    topics: [
      {
        title: 'Full-Stack Integration',
        subtopics: [
          {
            title: 'Connecting React to Express',
            description: 'Fetching from the API, in the browser.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'State & Persistence',
            description: 'Lifting state, saving to MongoDB.',
            difficulty: 'hard',
            estimatedTime: '1.5 hours',
            resources: [],
          },
          {
            title: 'Serving the Build',
            description: 'Express serving the frontend build.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
        ],
      },
      {
        title: 'Deployment',
        subtopics: [
          {
            title: 'Vercel (Frontend)',
            description: 'Deploying a Vite app.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Render (Backend)',
            description: 'Deploying an Express API.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'MongoDB Atlas',
            description: 'Cloud database & connection strings.',
            difficulty: 'medium',
            estimatedTime: '1 hour',
            resources: [],
          },
          {
            title: 'Environment & Locks',
            description: 'Setting env vars, CORS and secrets.',
            difficulty: 'medium',
            estimatedTime: '45 min',
            resources: [],
          },
        ],
      },
    ],
  },
];